name= "pastebin-worker"
compatibility_date = "2023-11-28"
account_id= "da9e5bc973418d10cb5e6fff74e5b0e7"
main = "src/index.ts"
workers_dev = false

vars = { ENVIRONMENT = "production" }
route = { pattern = "paste.617000.xyz", custom_domain = true }

kv_namespaces = [
  { binding = "PB", id = "5603529cbde14490b7faf6a169e99a6e" },
  { binding = "PBIMGS", id ="f777e2ea8883437bbaffceaf8db87116" }
]

[site]
bucket = "./static/dist"
